name: Deployment

on: push
  
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_IP }} 
          username: ${{ secrets.SERVER_USERNAME }} 
          key: ${{secrets.SERVER_KEY}}
          script_stop: true 
          command_timeout: 200m
          script: / 
            cd lucvkessel.nl
            git pull
            docker build -f Dockerfile.prod -t lucvkessel:prod .
            docker run -d --restart unless-stopped -p 3001:80 lucvkessel:prod
